apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 1700
      default_user = rabbitmq
      default_pass = rabbitmq
      default_user_tags.administrator = true
      prometheus.tcp.port = 15692
    additionalPlugins:
      - rabbitmq_prometheus
  persistence:
    storageClassName: local-path
    storage: 1Gi
  service:
    type: NodePort